language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6

env:
    - GRADLE_VERSION=2.2
    - GRADLE_VERSION=2.1

install:
    - ./gradlew wrapper -PgradleVersion=$GRADLE_VERSION

script: ./gradlew
