language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
  - openjdk7

env:
    - GRADLE_VERSION=2.2
    - GRADLE_VERSION=2.1
    - GRADLE_VERSION=2.0
    - GRADLE_VERSION=1.12
    - GRADLE_VERSION=1.11
    - GRADLE_VERSION=1.10
    - GRADLE_VERSION=1.9
    - GRADLE_VERSION=1.8
    - GRADLE_VERSION=1.7
install:
    - ./gradlew wrapper -PgradleVersion=$GRADLE_VERSION

script: ./gradlew
